events {}

http {
    resolver 10.89.0.1 valid=10s; # this will ask the Docker DNS server aboout the IP of container IP every 10s, because Docker assigns new IP after every reboot to the container 
    upstream flask_app {
        zone flask_app 64k;   # <--- allocate shared memory for dynamic resolution
        server app1:5000 resolve; # use resolve to make the DNS server request IP
        server app2:5000 resolve;
    }

    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 80;

        location / {
            proxy_pass http://flask_app;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Optional: timeout settings
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}